travis:
  secure:
    BINSTAR_TOKEN: XeAloerTgkQKahBRmogDiYbRt6qi2GD2cMxITKL4Jzf7jVaoCBs81jJy10qjxOVoZ3L4X/tKZ4UR90OOinVLcZcFkPG6XxUHVZ+qUHVfdcPP1Ll8gi/gOwSepR/KH1ZaFlePLI4PbA0s9Cwh5pInrSjrSkgI97aMXVeJ0YBB1kJT4kKGo4S9gE0+G/pH3Dja2bJGuf+5cLpEJfhYiIq3ia6mjTogY/hbx+FiPlHZ1Ao6Yy5GG5KDuawokIAcrqTtikb2UTBVWcqHZiWC6yQwNMd4e8SFysSzlgGPDZiYnIJi4UVi3FR/WsPSfSd+bSJwfxFRoWTLMasKKAhzhgzVuw/GBe7rrj/AAssyT5igirqLrD9HzY1gNrh6wKFX+7ulXbmKWiZ8ADcRRCLMd3pxMRj7iwgQKsJWcsoxd8/ACICsXMdpFarELKweY96Xr2YG2Y4qbp6173DzzwCTR6Nw+L0tRXbTMmACaWk0SvJKIne/QdQFqAHDKDrD926/OneqAtVhh4HIUfIuGb4HxNi8cpeTdpyXCC84D/UTIM+Pt1WgvJBWXRQLX8Zu+2ZVVnZWTBHMgGfHbIyQtMQf5O7tySCmjWOG4SSpgxAKkckLKV5uFclXMthAtyhPk6bIsk0HRoZfu1pZSlxoYYMo/TDYWPs0b4wEvR0pnpm7NM3wHJ0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
