travis:
  secure:
    BINSTAR_TOKEN: btUZw0nCHW+1V9vr9pM1aRcPeNgHGybifW4r2fI0V1N4XhZUn3o6jHWTWUFy/D0neiDldJO6iQSERzS2ZK4aCwxY3K0Lt4kQftAQ4E9RvYSlo6OcfG67wivbhLs0+qpvL/R118l8QXwUk4n3qRHrc+cr8B8ryfHDO+j07qaCWe6KKOXKHv+3sRW8tm9xomkQlGFzDeE/47O1XgWF4p43Dier2mQf4RDSAIxHOyHWZxYMa5PS5ei9aWqQ8bhTLsN73ANardlqteCii1Z4nmSGt5fa7t5obahzSsoqksjYA5mF12cyNkIX6HyNz+uuFWDgwtzR1xCOQK/GyPdG7ATDxO/Ce9jFPsR3BZ/J8KN9X4h7jTOm+s5qBdm5XSC8+VSEGIGdpy+btcrUySWK4HYzwtwH0bIcDl3y/vIiRw4fvJA5+ZKFeOzqg+0LCGm8bkNM0Vkzp9oTRFho/tDj7D9ilRiyMU6LE6tDs990onlWRMORInQFgdcngVJcf2t1i9QhohI2inrtF8xXQPz5zZdD/HOW2wbRFXJ5YfLSVUgMW6fzK55VTDGtW72IC7pMviFFEHZvdew9C7CE9CGUNb3nxBWQLLBSD3zqARns3dOiKR2m0o6w3GNkFLJr+XmprOfIdcuVjs36oMg/wtMi5NqzfEL4GrYURcKykC9EDsA95yY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
