travis:
  secure:
    BINSTAR_TOKEN: QIL9q/VqQ4nD3y58EkmE0KDvuB0xngjClwqfVzhEu3oA8K+/E42JNTi68UZoLEpWhEno8kiC6icfl2RkeoBrFnxTPRPFAh3HSuC58oUTHH47grY06PUJ05Mt43E17g93NUCgncr4M6YJ9CxPIzGH075LhZLLf2eVewqYHdtQvbBfkZfhxNtgZq5n/V4xd4BN5iAaOF39uBI9jN8kSAre1TVQENvVkmWEdrwMNkNy3KB8I1iGYY3+owZh9Vk58duknKBYXMmBPReUgKl2xXyJppGj3bnsrg0+8xwuOzLAr/DCMFhFCF4nwxWOdPvlxh+JgHSeat8KP3v8ghKJb4dbRovcCUXVN95Q41Y29nCOhn/xe6KcIqbn2qJ6hnqz2PSperemSrm4jcgRLAeQW/bFSAAAFIaXS2hjZkvfdtg9sI7rBOfFuU4va3VSarIa+7HFb103doS2b+bl5q7kVp3iMPowljRjeGVLtA03nNqp7GnwRGLtx5JzzbWoR9+ir96ET5JVSrIbE0UklbyQagapDAe/qQVBlli3D/CirYCWcokjjoWvtkMBsvDnesoQR+sLqtx6XSNrJthS0Iz85XWHv8WVluW8PFkKT5LsvCQwumR2WzTqtVPo69PWLTnv+06LRMDjZgigoVAV3X1Zud35aCt6/+TT5EwqukdH1jthb/I=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
